### PR TITLE
Object storage updates

### PR DESCRIPTION
**Pull request by scross01**
- Adds `metadata` block to `opc_storage_container` for custom meta data headers
- Adds `metadata` block to `opc_storage_object` for custom meta data headers
- Adds `quota_bytes` and `quota_count` attributes to `opc_storage_container`
- Fixed and updated docs for `opc_storage_container` and `opc_storage_object`

### CODE REVIEW

**Comment by mbfrahry** [comment]
We'll have to cut a new release for the sdk and get those changes over here. Also, since these are PaaS changes, how would you feel about holding off on these changes until we make the new PaaS provider?

**Comment by scross01** [comment]
Object Storage is considered an Infrastructure service, not PaaS, so would stay as part of the `opc` provider. Not sure why it had been labeled PaaS before, I fixed the reference in the docs.

**Comment by mbfrahry** [comment]
Oh! That's really good to hear. I was worried we'd have to do some shenanigans to get it into the PaaS provider but this makes the path forward a lot easier.

**Comment by mbfrahry** [comment]
I've updated this PR with the latest version of the sdk if you want to take a crack at finishing it up

**Pull request merged**
